# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfiguration.proto\x12\x04info\"U\n\rConfiguration\x12\x1d\n\x15\x66\x61ult_tolerance_level\x18\x01 \x01(\x05\x12%\n\x0bmethod_type\x18\x02 \x01(\x0e\x32\x10.info.MethodType* \n\nMethodType\x12\x08\n\x04STRT\x10\x00\x12\x08\n\x04STOP\x10\x01\x42&\n\x10\x63omm.struct.infoB\x12\x43onfigurationProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020comm.struct.infoB\022ConfigurationProto'
  _globals['_METHODTYPE']._serialized_start=116
  _globals['_METHODTYPE']._serialized_end=148
  _globals['_CONFIGURATION']._serialized_start=29
  _globals['_CONFIGURATION']._serialized_end=114
# @@protoc_insertion_point(module_scope)
