# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x04info\"I\n\x07Message\x12\x1c\n\x06\x64\x65mand\x18\x01 \x01(\x0e\x32\x0c.info.Demand\x12 \n\x08response\x18\x02 \x01(\x0e\x32\x0e.info.Response*\x1d\n\x06\x44\x65mand\x12\t\n\x05\x43PCTY\x10\x00\x12\x08\n\x04STRT\x10\x01*\x1c\n\x08Response\x12\x07\n\x03YEP\x10\x00\x12\x07\n\x03NOP\x10\x01\x42 \n\x10\x63omm.struct.infoB\x0cMessageProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020comm.struct.infoB\014MessageProto'
  _globals['_DEMAND']._serialized_start=98
  _globals['_DEMAND']._serialized_end=127
  _globals['_RESPONSE']._serialized_start=129
  _globals['_RESPONSE']._serialized_end=157
  _globals['_MESSAGE']._serialized_start=23
  _globals['_MESSAGE']._serialized_end=96
# @@protoc_insertion_point(module_scope)
